name: release

on:
  workflow_dispatch:

jobs:
  release:
    # ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          make build
          docker build -t ghcr.io/scmtble/cadvisor:beta -f ./deploy/Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: |
          docker push ghcr.io/scmtble/cadvisor:beta